### PR TITLE
Asr1k job logic

### PR DESCRIPTION
**Pull request by tiswanso**
# Summary:
* Topo is very similar to nexus test with the following additions:
    * preconfig trunk all claimed vlans for switchport for VM under test + switchports to ASR1K
    * setup a VLAN sub-interface on the vlan used for the job's private ext-net (min vlan) so
       tempest can access VMs via FIP implemented by ASR1K.
* local.conf built from nested templates for both ASR1K and nexus jobs
    * top level templates:  nexus_job_local_conf.j2, asr1k_job_local_conf.j2
    * lconf_netcisco_common = enable networking-cisco
    * lconf_common_vlan = OVS ML2 & vlan range / physnet config 
    * lconf_*_glbl.j2 = job specific global lconf config
    * lconf_common_postcfg_neutron_conf = common neutron.conf settings (net-cisco svc, MTU)
    * <job specific *.conf file settings>

# Considerations for ASR1K scenario:
* ASR1K HA pair used in each test job
* ASR1K plugin disables l3-agent
* metadata svr needs to run in dhcp namespace
   * see ENABLE_ISOLATED_METADATA=True, force_metadata = True
* VLANs need to be trunked to switchports connecting ASR1K pair
   * see how "nexus_interfaces" is appended with ports connected to each ASR1K
* devstack VM host sub-interface on ASR1K ext-net VLAN needed for
  tempest to access floating IPs.
   * uses role setup-vlan-subinterface
* ASR1K plugin supports specific sets of API extensions
   * see NETWORK_API_EXTENSIONS
* ASR1K plugin doesn't support IPv6 neutron subnets, yet
   * local.conf template disables ipv6
* Patch needed to devstack to allow creating VLAN provider net with router external attrib set.

[Topo & job info](https://wiki.cisco.com/display/OPENSTACK/Networking-Cisco+CI+Notes#Networking-CiscoCINotes-ASR1KJobInfo)

# Additional implementation notes:
* devstack local.conf built from nested templates 
   * allows sharing of code for common test infra
      * topo approaches, ie. VLAN type networks
   * allows for composable approach for adding interworking tests (ie. ASR1K & nexus plugins
   together scenario).
* Added dicts to group_vars for device credentials and port connectivity.  
   Could be used for nexus    as well but didn't modify those existing parts.
* job & version specific devstack patches loaded via existing macro in custom_devstack_gate_hook

### CODE REVIEW

**Comment by Tehsmash** [comment]
Running full experimental CI run against the networking-cisco master branch https://review.openstack.org/#/c/516366/

**Comment by Tehsmash** [comment]
This patch passed everything except the pike and ocata branches. I know pike is not supposed to pass, but Ocata was passing before the patch merged to networking-cisco for the devstack changes, so not sure what has happened there, but other than that this patch is more or less good to go I think. I've also put up a patch to add the pipeline and jobs to networking-cisco's normal CI runs here #42, so once this merges that can merged ASAP too.

**Comment by tiswanso** [comment]
On PTO today but I checked the Ocata test logs for  https://review.openstack.org/#/c/516366.  It doesn’t look like there’s any issue related to the job setup or the networking-cisco devstack plugin.  It’s stacking and local_conf settings seem fine from a quick run through.

The test_network_basic_ops is failing on FIP ping:

TestNetworkBasicOps:test_network_basic_ops finishes ping 10.254.0.19 in 120 sec and the ping result is expected

Looking at the world-dump, the devstack host seems setup fine — nexustap2.2000 is setup correctly as the external-net GW (10.254.0.1).   Looking at the q-ciscocfgagent log, I don’t see any errors and there’s definitely FIP setup stuff happening on the ASRs for 10.254.0.19 and I see the external net interfaces on the ASR are setup ok.

Checked the console log and I don’t see any setup issues of VLAN 2000, etc on each interface— 1/17, 1/18, 1/21, 1/22.

My hunch is that there’s some timing issue or something here, possibly a recheck would pass (ocata).  IMO, even with this failure it’s good to merge and we can get the other folks’ help on why there’s failures in that one test.

Also, we should sync up about testing parallelization of those ASR jobs.  I know you were working on a common script/lib for setting up/reserving multi-job state in the mysql pools.  If that’s ready I could try stuff out.  I think I’d need your help in populating the initial mysql table, though — permissions?

Anyway, thanks for reviewiing and PR #42!  Will talk to you tomorrow.  —Tim


On Jan 15, 2018, at 9:27 AM, Sam Betts <notifications@github.com<mailto:notifications@github.com>> wrote:


This patch passed everything except the pike and ocata branches. I know pike is not supposed to pass, but Ocata was passing before the patch merged to networking-cisco for the devstack changes, so not sure what has happened there, but other than that this patch is more or less good to go I think. I've also put up a patch to add the pipeline and jobs to networking-cisco's normal CI runs here #42<https://github.com/CiscoSystems/project-config-third-party/pull/42>, so once this merges that can merged ASAP too.

**Comment by tiswanso** [comment]
More info on the failure in http://192.133.156.18/66/516366/11/experimental/gate-networking-cisco-dsvm-tempest-smoke-asr1k-ocata-centos-7-asr/9069559/logs/testr_results.html.gz.

The FIP ping failure is seen after several passed FIP pings and ssh connects to corresponding VMs.  I think the fail is a subtest failure hitting a FIP ping failure after re/attaching a FIP to a new VM.  Maybe there's a timing issue that can pop up with the ASR plugin and rapid FIP add/remove ops.

From the point of view of this PR, the successful ssh connections confirm everything is setup ok job-wise and this is an actual test failure due to the resulting openstack behavior.  So, IMO, that failure shouldn't block this PR.

**Comment by cisco-openstack** [comment]
Hi Tim, Sam,

That is an issue we’ve seen and Sridar has a patch that should at the very least mitigate it (if not entirely fixing it).
We’ve not merged it yet as he is still working on UTs for the patch.

So, I agree with your conclusion.

Thanks,
Bob

**Pull request merged**
